version: '3.5'

services:

  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000"

  db:
    image: "postgres:11"
    container_name: "postgres_tree"
    ports:
      - "54320:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks: 
      - default
    environment:
      - POSTGRES_DB=db_tree
      - POSTGRES_USER=user_db
      - POSTGRES_PASSWORD=testetree#123
volumes:
  static_volume:
